databaseType = "PostgreSql"
id = "37a60e5f-08a4-4deb-9bc4-8fec9491c958"
name = "totmapi"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.totm-local]
url = "jdbc:postgresql://localhost:5432/"
schemas = [ "richard" ]
displayName = "totm-local"

[environments.totm-prod]
url = "jdbc:postgresql://dpg-ctblrft6l47c73b2hj4g-a.frankfurt-postgres.render.com:5432/totmdb"
schemas = [ "totm" ]
